In [3]:
import pandas as pd

In [19]:
cars_df = pd.read_csv("cars.csv",sep=";", skiprows=[1])
e_cars_df = pd.read_csv("e-cars.csv",sep=";")
earthquakes_df = pd.read_csv("earthquakes.csv")

In [51]:
e_cars_df

Index(['YEAR', 'Make', 'Model', 'Size', '(kW)', 'Unnamed: 5', 'TYPE',
       'CITY (kWh/100 km)', 'HWY (kWh/100 km)', 'COMB (kWh/100 km)',
       'CITY (Le/100 km)', 'HWY (Le/100 km)', 'COMB (Le/100 km)', '(g/km)',
       '(km)', 'TIME (h)'],
      dtype='object')

In [62]:
e_cars_df.corr(numeric_only=True)

,YEAR,(kW),CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),(km),TIME (h)
YEAR,1.000000,0.303071,0.046792,-0.264488,-0.034193,0.045727,-0.270912,-0.034914,NaN,0.234407,0.139391
(kW),0.303071,1.000000,0.827555,0.046083,0.706847,0.823125,0.047220,0.721353,NaN,0.894615,0.757326
CITY (kWh/100 km),0.046792,0.827555,1.000000,0.442151,0.965258,0.996966,0.437810,0.966911,NaN,0.906960,0.806459
HWY (kWh/100 km),-0.264488,0.046083,0.442151,1.000000,0.657155,0.447289,0.986524,0.623550,NaN,0.166217,0.316639
COMB (kWh/100 km),-0.034193,0.706847,0.965258,0.657155,1.000000,0.964408,0.652038,0.990175,NaN,0.807819,0.763181
CITY (Le/100 km),0.045727,0.823125,0.996966,0.447289,0.964408,1.000000,0.443211,0.968351,NaN,0.907392,0.798633
HWY (Le/100 km),-0.270912,0.047220,0.437810,0.986524,0.652038,0.443211,1.000000,0.609502,NaN,0.144554,0.256665
COMB (Le/100 km),-0.034914,0.721353,0.966911,0.623550,0.990175,0.968351,0.609502,1.000000,NaN,0.821189,0.781931
(g/km),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(km),0.234407,0.894615,0.906960,0.166217,0.807819,0.907392,0.144554,0.821189,NaN,1.000000,0.879352
TIME (h),0.139391,0.757326,0.806459,0.316639,0.763181,0.798633,0.256665,0.781931,NaN,0.879352,1.000000

In [68]:
earthquakes_df.corr(numeric_only=True)

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
cdi,1.000000,0.187996,0.268136,-0.146190,0.399337,0.646273,0.326456,0.285521,0.496059,-0.053730,0.152761,0.218833,0.071744
dmin,0.187996,1.000000,-0.026284,0.004667,0.473606,-0.534080,-0.205622,0.450838,0.513970,-0.016757,0.074724,0.364648,0.123581
felt,0.268136,-0.026284,1.000000,-0.148835,0.167702,0.080612,0.461274,0.017168,0.241496,0.028253,0.162864,-0.019137,0.163356
gap,-0.146190,0.004667,-0.148835,1.000000,-0.051751,-0.204260,-0.531402,-0.060453,-0.064927,-0.022815,-0.094786,-0.036809,-0.011736
mag,0.399337,0.473606,0.167702,-0.051751,1.000000,0.143664,0.351382,0.610893,0.915157,0.024952,0.260269,0.579527,0.188736
mmi,0.646273,-0.534080,0.080612,-0.204260,0.143664,1.000000,0.275441,0.092323,0.302261,0.084416,0.559591,0.365396,0.110450
nst,0.326456,-0.205622,0.461274,-0.531402,0.351382,0.275441,1.000000,0.104234,0.283560,0.005201,0.051673,-0.164782,0.012179
rms,0.285521,0.450838,0.017168,-0.060453,0.610893,0.092323,0.104234,1.000000,0.553085,-0.026704,0.157305,0.278388,0.194743
sig,0.496059,0.513970,0.241496,-0.064927,0.915157,0.302261,0.283560,0.553085,1.000000,0.011342,0.366343,0.682710,0.147120
time,-0.053730,-0.016757,0.028253,-0.022815,0.024952,0.084416,0.005201,-0.026704,0.011342,1.000000,0.018205,0.006315,0.843418
tsunami,0.152761,0.074724,0.162864,-0.094786,0.260269,0.559591,0.051673,0.157305,0.366343,0.018205,1.000000,0.290775,0.006010
tz,0.218833,0.364648,-0.019137,-0.036809,0.579527,0.365396,-0.164782,0.278388,0.682710,0.006315,0.290775,1.000000,0.044224
updated,0.071744,0.123581,0.163356,-0.011736,0.188736,0.110450,0.012179,0.194743,0.147120,0.843418,0.006010,0.044224,1.000000

In [63]:
cars_df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
4,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4,140.0,86.0,2790.0,15.6,82,US
402,Volkswagen Pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe
403,Dodge Rampage,32.0,4,135.0,84.0,2295.0,11.6,82,US
404,Ford Ranger,28.0,4,120.0,79.0,2625.0,18.6,82,US
405,Chevy S-10,31.0,4,119.0,82.0,2720.0,19.4,82,US

In [69]:
cars_df.corr(numeric_only=True)

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model
MPG,1.000000,-0.735563,-0.764277,-0.726670,-0.787510,0.424490,0.586234
Cylinders,-0.735563,1.000000,0.951787,0.823467,0.895220,-0.522452,-0.360762
Displacement,-0.764277,0.951787,1.000000,0.873758,0.932475,-0.557984,-0.381714
Horsepower,-0.726670,0.823467,0.873758,1.000000,0.840811,-0.682047,-0.419929
Weight,-0.787510,0.895220,0.932475,0.840811,1.000000,-0.430086,-0.315389
Acceleration,0.424490,-0.522452,-0.557984,-0.682047,-0.430086,1.000000,0.301992
Model,0.586234,-0.360762,-0.381714,-0.419929,-0.315389,0.301992,1.000000

In [79]:
#earthquakes_df.drop(["url", "dmin"], axis=1 , inplace=True)
earthquakes_df.columns = ['alert', 'Max intenzitet', 'šifra', 'Min. raz. st.', 'Po osjetu', 'Azimutni raz. izm. st.', 'ids', 'mag', 'magType',
       'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources', 'status', 'time',
       'title', 'tsunami', 'type', 'types', 'tz', 'updated', 'url']

Index(['alert', 'cdi', 'code', 'dmin', 'felt', 'gap', 'ids', 'mag', 'magType',
       'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources', 'status', 'time',
       'title', 'tsunami', 'type', 'types', 'tz', 'updated', 'url'],
      dtype='object')

In [81]:
earthquakes_df["felt"]

0        NaN
1        NaN
2       28.0
3        NaN
4        NaN
        ...
9327     NaN
9328     NaN
9329     NaN
9330     NaN
9331     NaN
Name: felt, Length: 9332, dtype: float64